version: '3.3'
services: 
  postgres:
    image: 'postgres:latest'
    restart: always
    volumes:
      - './compose_postgres_db/postgres_data:/var/lib/postgresql/data'
    environment:
#      - PUID=1000
#      - PGID=1000
      - POSTGRES_PASSWORD=123456
    expose:
      - "5432"

  backend_users:
    build: ../taller2-ubademy-users
    container_name: compose_backend_users
    image: backend_users
    expose:
      - "8001"
    ports:
      - "8001:8001"
    volumes:
      - ./../taller2-ubademy-users:/app
    depends_on:
      - postgres

